title: Plugdata and Daisy for starters
description: A beginners components library for using Plugdata to program a Daisy 
theme: just-the-docs

url: https://jonwaterschoot.github.io/plugdata-daisy-simple/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  jonwtr: https://jonwtr.be

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: grey-dk
  new:
    title: New
    color: green
  note:
    title: Note
    color: grey-lt
  warning:
    title: Warning
    color: red


kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
