title: Plugdata and Daisy for starters
description: A beginners components library for using Plugdata to program a Daisy 
# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

url: https://jonwaterschoot.github.io/plugdata-daisy-simple/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  jonwtr: https://jonwtr.be

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

